package app

import (
	"fmt"
	"os"
)

const defaultConfig = `# .releaseguard.yml — generated by releaseguard init
# Full schema: https://github.com/Helixar-AI/ReleaseGuard/docs/config-schema.md
version: 2

project:
  name: my-app
  mode: release

inputs:
  - path: ./dist
    type: directory

sbom:
  enabled: true
  ecosystems: [node, python, go, rust, java, dotnet]
  formats: [cyclonedx]
  enrich_cve: false
  fail_on_cvss_above: 9.0
  allowed_licenses:
    - MIT
    - Apache-2.0
    - BSD-2-Clause
    - BSD-3-Clause
    - ISC

scanning:
  secrets:
    enabled: true
  metadata:
    enabled: true
    fail_on_source_maps: true
    fail_on_internal_urls: true
  unexpected_files:
    enabled: true
    deny:
      - ".env"
      - "*.map"
      - ".git/**"
      - "*.bak"
      - "*.tmp"
  licenses:
    enabled: true
    require:
      - LICENSE

transforms:
  remove_source_maps: true
  delete_forbidden_files: true
  add_checksums: true
  add_manifest: true
  normalize_timestamps: true

obfuscation:
  enabled: false
  level: light  # medium/aggressive: ReleaseGuard Cloud only

drm:
  enabled: false
  integrity_check:
    enabled: false
    on_tamper: exit

signing:
  enabled: false
  mode: keyless
  subject: "releaseguard-ci"

attestations:
  enabled: false
  provenance: true
  evidence: true
  sbom: true

policy:
  fail_on:
    - severity: critical
    - severity: high
    - category: secret
  warn_on:
    - category: missing_notice
  require_sbom: false
  require_obfuscation: none
  require_integrity_check: false

output:
  reports:
    - cli
    - json
  directory: ./.releaseguard
`

// Init writes a default .releaseguard.yml to the current directory.
func Init() error {
	const configFile = ".releaseguard.yml"

	if _, err := os.Stat(configFile); err == nil {
		return fmt.Errorf("%s already exists — delete it first if you want to regenerate", configFile)
	}

	if err := os.WriteFile(configFile, []byte(defaultConfig), 0644); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	fmt.Printf("Created %s\n", configFile)
	fmt.Println("Edit the file to match your project, then run: releaseguard check ./dist")
	return nil
}
